#!/usr/bin/env bash

# remove ./ from the beginning of file names
function strip_dir_head {
    echo $1 | sed -E "s$\./(.*)$\1$"
}

# get all of the files in this directory
FILES=`find . -maxdepth 1 -mindepth 1`

echo ".PHONY: unlink kill link backup"
echo "PWD := \$(shell pwd)"

echo -en "\ndotfiles ="
for file in $FILES; do
stripped=`strip_dir_head $file`
echo -en " ~/$stripped"
done

echo -en "\n
link: \$(dotfiles)
"

# Generate the make commands
for file in $FILES; do
stripped=`strip_dir_head $file`
echo -en "
~/$stripped: $file
\tln -s `echo '$(PWD)'`/$stripped ~/$stripped
"
done

echo -en "
unlink:
\tfor file in \$(dotfiles); do if test -L \\\$file; then rm ~/\\\$file; fi; done;
"
echo -en "
kill:
\trm -rf \$(dotfiles)
"
echo -en "
backup:
\tif [ ! -d .backup ]; then mkdir .backup; fi
\tfind ~ -maxdepth 1 -type f -or -type d -name '.*' | \
    xargs -I % cp -rv % $PWD/.backup
"
