#!/usr/bin/env python
import sys
from collections import defaultdict

names = defaultdict(list)
for line in sys.stdin:
    hash, fname = line.split(" ", 1)
    names[hash].append(fname.strip())

for nset in names.itervalues():
    if len(nset) <= 1: continue
    sset = sorted([(len(x), x) for x in nset])
    _, smallest = sset[0]
    for (_, name) in sset[1:]:
        sys.stderr.write("Dupe: '{0}' (of '{1}')\n".format(name, smallest))
        print name
