#!/usr/bin/env python

from argparse import ArgumentParser
import sys
import random

parser = ArgumentParser()
parser.add_argument("-n", "--count", type=int, 
                    help="Pick 'n' results.")
args = parser.parse_args()

buf = []

seen = 0
for line in sys.stdin:
    if seen < args.count:
        buf.append(line)
    else:
        # Select a random number from "seen" possible values
        rand = random.randint(0, seen - 1)
        # if we select one of the args.count items (args.count-1 possible)
        if rand <= (args.count - 1):
            # Then replace that entry in the buffer with the value we picked
            buf[rand] = line
    seen += 1

# print the buffer
for line in buf:
    print line,
