#!/usr/bin/env bash
if [[ "$1" = "" && ! -f "$1" ]]; then
    echo "Invalid Exclude file '$1'."
    exit 1;
fi

rsync -hurtmv --progress \
    --modify-window=1 \
    --delete-before --delete-excluded \
    --include-from="$1" \
    ~/music/library/ /Volumes/MUSIC/
