#!/usr/bin/env bash
# rsync
# --progress: Display transfer progress
#         -r: recursive
#         -h: human readable
#         -v: verbose
#         -t: copy times
#         -u: update

REMOTE_SRC="desktop:~/music/"
LOCAL_SRC="$HOME/Music/Library/"

# Sync remote -> local
rsync --progress -rhvtu $REMOTE_SRC $LOCAL_SRC 
# Sync local -> remote
rsync --progress -rhvtu $LOCAL_SRC $REMOTE_SRC 
